### ISSUE TITLE
[BE] Prevent option to choose user's own team in send_challenge view

### ISSUE THREAD

**Issue by Miecznikk** [Miecznikk/PlayArena#10]

**Comment by valdife** [comment]
![image](https://user-images.githubusercontent.com/46005237/225863924-0cd4cae5-b5ad-43b8-bbd1-51d8fa268638.png)
starting from line 63, isn't it the fix?

**Comment by valdife** [comment]
@Miecznikk

**Comment by Miecznikk** [comment]
@valdife to jest walidacja, mi w tym fixie chodziło o to, żeby w ogóle nie można było tego wybrać w formie, nie bede pisal tu po angielsku bo to yikes i cringe

**Comment by Miecznikk** [comment]
źle nazwałem issue może, my bad

**Comment by valdife** [comment]
closing this one, there is validation for that and changing whole template for this one feature is overkill
