### ISSUE TITLE
[BE] Implement functionality for leaving team and give up captain role

### ISSUE THREAD

**Issue by Miecznikk** [Miecznikk/PlayArena#12]
Note that if a captain wants to leave a team it should not be possible until he gives up his role

**Comment by valdife** [comment]
Can I resolve it by setting captain role on random player that is in the team?

**Comment by Miecznikk** [comment]
sure bartosz you can

**Comment by valdife** [comment]
closing this one, there is validation for that and changing whole template for this one feature is overkill

**Comment by valdife** [comment]
https://github.com/Miecznikk/PlayArena/pull/36
